### ISSUE TITLE
Vendor Folder is Missing (Necessary for Composer Autoload)

### ISSUE THREAD

**Issue by jkhaui** [buddypress/bp-graphql#1]
The plugin cannot be activated because 'vendor/autoload.php' is not included.

I tried using the vendor folder from the WP GraphQL plugin in its place; got BP-GraphQL to activate but it ruined the existing WP schema

**Comment by slaFFik** [comment]
Have you ran `composer install` in terminal from `bp-graphql` directory?

**Comment by renatonascalves** [comment]
@jkhaui Locally, you need to run the command @slaFFik shared above. Going to close this issue as invalid, but feel free to ask any question. =)

**Comment by jkhaui** [comment]
Oops, sorry about that! I don't work with PHP much so didn't notice the composer.json file :)

**Comment by jkhaui** [comment]
Hey :)

I'm trying to experiment by extending the Group Type to include a **list** of groups (allowing you to query "groups" to return all groups, instead of "group (id: 1)", "group (id: 2)", etc.).

I've tried looking over the WP-GraphQL post types to get an idea of how this might be done, but to be honest I found the documentation lacking.. Do you have any pointers for how I could make a start on this?

**Comment by renatonascalves** [comment]
@jkhaui You can use the comments implementation of the wp-graphql as an example. It's almost the same thing.

I started doing that a few weeks/months ago but haven't finish it yet. If you do start on it soon, send a PR.
